kind: ConfigMap
apiVersion: v1
metadata:
  name: local-zfs-provisioner-config
  namespace: kube-system
data:
  config.json: |-
    {
        "nodeDatasetMap": [
            {
                "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
                "dataset": "zfspool/k3s"
            }
        ]
    }

