# apiVersion: scheduling.k8s.io/v1
# kind: PriorityClass
# metadata:
#   name: low-priority-class
# value: 10
# globalDefault: false
# description: "This priority class should be used for low priority fah-cpu pods only."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foldingathome-cpu
  labels:
    app: fah-cpu
spec:
  selector:
    matchLabels:
      app: fah-cpu
  # Set number of replicas to run - one replica per node
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: fah-cpu
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fah-cpu
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: fah-cpu
          image: "richstokes20/fah-covid:latest"
          # --run-as UID should match runAsUser value in containers securityContext
          command:
            - "/usr/bin/FAHClient"
            - "--config"
            - "/var/lib/fahclient/config.xml"
            - "--config-rotate=false"
            - "--run-as"
            - "1234"
            - "--pid-file=/var/lib/fahclient/fahclient.pid"
            - "--gpu=false"
          resources:
            limits:
              # How much CPU you wish to donate per node
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          # Make the container harder to break out of or exploit
          securityContext:
            runAsNonRoot: true
            runAsUser: 1234
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/lib/fahclient/
              name: fahclient-storage
      # We make an emptyDir to mount on the work directory /var/lib/fahclient
      # so we can make the rest of the container's root filesystem read-only
      volumes:
        - name: fahclient-storage
          persistentVolumeClaim:
            claimName: fah-local-zfs-pvc
        # Uncomment if using ConfigMap config.xml
        - name: fah-cpu-config
          configMap:
            name: foldingathome-config
      initContainers:
        - name: copy-config
          imagePullPolicy: Always
          image: "richstokes20/fah-covid:latest"
          command:
            - "sh"
            - "-c"
            # - "cp /etc/fahclient/config.xml /var/lib/fahclient/config.xml"
            # Use this cp command instead if using ConfigMap config.xml
            - "cp /etc/fahclient-config/config.xml /var/lib/fahclient/config.xml"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1234
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /var/lib/fahclient
              name: fahclient-storage
            # Uncomment if using ConfigMap config.xml
            - name: fah-cpu-config
              mountPath: /etc/fahclient-config
            # priorityClassName: low-priority-class
