apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-local-zfs-pvc
  namespace: network-daemons
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-zfs
  resources:
    requests:
      storage: 1Gi